site_name: Sylvan's Blog
docs_dir: blog
theme:
  name: material
  custom_dir: overrides
plugins:
    - search
    - awesome-pages
    - markdownextradata
    # custom plugins
    - git-dates
markdown_extensions:
  - meta
