name: Kubernetes Deployment

on:
  # Allows this workflow to be called by other workflows
  workflow_call:
    inputs:
      release_tag:
        description: "Tag of docker image used for deployment"
        type: string
        required: true
      kubernetes_namespace:
        description: "Namespace in which application will be deployed"
        type: string
        default: default
    secrets:
      KUBERNETES_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO: replace envsubst by helm in this workflow ?
      - name: Set environment variables for envsubst
        run: |
          echo "DEPLOYED_VERSION=${{ inputs.release_tag }}" >> $GITHUB_ENV

      # Setup kubectl to deploy our app
      - uses: azure/setup-kubectl@v1
        with:
          version: "v1.21.0"

      # Retrieve kubectl config from secrets
      - name: Configure kubectl to use org cluster
        run: |
          mkdir ~/.kube
          cat <<-EOF > ~/.kube/config
          ${{ secrets.KUBERNETES_CONFIG }}
          EOF

      # Use kubectl to deploy application (substitute current env vars in deployment.yml)
      - name: Deploy application using kubernetes
        run: cat deployment.yml | envsubst | kubectl apply -n "${{ inputs.kubernetes_namespace }}" -f -
